CREATE DATABASE stroll;
use stroll;
CREATE TABLE place(
	no INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100),
    content TEXT(500),
    writtenDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    address CHAR(80) NOT NULL,
    detailAddress VARCHAR(80),
    x DECIMAL(8,6) NOT NULL,
    y DECIMAL(9,6) NOT NULL
)