CREATE DATABASE stroll;
use stroll;
DROP TABLE IF EXISTS place;
CREATE TABLE place(
	no INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(100),
    content TEXT(500),
    category char(20),
    writtenDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    address CHAR(80) NOT NULL,
    detailAddress VARCHAR(80),
    x double NOT NULL,
    y double NOT NULL,
    userId CHAR(20) NOT NULL,
    CONSTRAINT fk_place_user_id FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);



DROP TABLE IF EXISTS user;
CREATE TABLE user(
	id CHAR(20) PRIMARY KEY,
    password CHAR(20) NOT NULL,
    nickname CHAR(20) NOT NULL UNIQUE,
    email CHAR(50) NOT NULL
);

DROP TABLE IF EXISTS reply;
CREATE TABLE reply(
	no INT PRIMARY KEY AUTO_INCREMENT,
	userId CHAR(20) NOT NULL,
    placeNo int NOT NULL,
    content TEXT(500),
    star TINYINT,
    writtenDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_reply_user_id FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE
);